### ISSUE TITLE
Add Article for Reverse a String in Scheme

### ISSUE THREAD

**Issue by jrg94** [jrg94/sample-programs#150]
@frpeters was kind enough to write up Reverse a String in Scheme. I'll need to remember to mention them in the article when I get around to it!

**Comment by awoerner92** [comment]
@jrg94 Do you still need help with this? My scheme skills are a bit rusty, but this would be a nice opportunity to dig into it again :)

**Comment by jrg94** [comment]
I can always use the help! Send me your preferred email address to jeremy.grifski@therenegadecoder.com. Then, I'll set you up with an author account on the site. ✔️

**Comment by awoerner92** [comment]
I finished the first draft. Let me know where it needs improvements when you come around to reading it.

**Comment by jrg94** [comment]
Sounds great! I'll take a look shortly.

**Comment by jrg94** [comment]
By the way, the article is excellent! 💯 Do you have any preference for [featured images](https://pixabay.com/)?

**Comment by awoerner92** [comment]
Thank you! No, I'll leave the decision to you.

**Comment by jrg94** [comment]
Sounds great. I'm going to schedule your article for July 16th. In the meantime, let me know if you need anything.

**Comment by jrg94** [comment]
Also, I added the link to the article to the README already: https://github.com/jrg94/sample-programs/commit/c25493d797f7e966643f2a4b1a21cdc8e8374130
