### ISSUE TITLE
Add Article for Hello World in PowerShell

### ISSUE THREAD

**Issue by jrg94** [jrg94/sample-programs#203]
Thanks again, @AaronLenoir! Source: #202

**Comment by Alcha** [comment]
@jrg94 I've written the first draft of an article and uploaded it [as a gist][1]. If you could take a look at it and let me know if I'm on the right track I'll get it cleaned up and ready for you to properly post.

[1]: https://gist.github.com/Alcha/e5d3c0d5cee0f61555540566336cf4ca

**Comment by jrg94** [comment]
Wow! This is excellent. I typically write the articles myself, but I'm more than happy to post your article. 

That said, I've never had a guest post, so I may need to figure out how to make an author profile for you.

**Comment by Alcha** [comment]
No worries, I'm not in any rush. As I mentioned that was a first draft so I'm sure there's plenty that could be cleaned up.

That said, if you don't want to hassle with a guest profile you can post it under yours with an underlined note at the top that it's a guest article written by me.

**Comment by jrg94** [comment]
Alright, I created an account for you. I believe you got an email about it. You should be able to get in and create your own articles as a [Contributor](https://thethemefoundry.com/blog/wordpress-user-roles/). I'm sure there's also a profile you can write up if you want which will display at the bottom of the article.

**Comment by Alcha** [comment]
Hey @jrg94, I saved a draft of the post that looks good to post but WordPress keeps telling me I need to add a featured image and I can't find where in the hell to _add_ the featured image...

I attached an image above all the text in hopes that would do it but to no avail. Any help would be appreciated.

**Comment by jrg94** [comment]
Yeah, I think that's my fault. I have a plugin that blocks publishing without a featured image, and I believe your role doesn't have permission to add one.

If you're happy with the article, I'll add a featured image and schedule it for tomorrow @ 10:00AM. 👍

**Comment by jrg94** [comment]
Also, your profile will appear at the bottom of the post. You should be able to edit your profile on the backend to include social media links and a description about yourself if you want.

**Comment by Alcha** [comment]
I honestly wasn't too sure how to end it without just copy/pasting your previous entries in the Hello World series so I didn't add that part. 

If it really _is_ just a copy paste, then I'll go ahead and add it.

Aside from that, it looks good to go as far as I'm concerned so it's ready to be published 😊

**Comment by Alcha** [comment]
Actually just went ahead and added the **Sample Programs in Every Language** section since I noticed it's only a sentence or two. Just needs a feature image and then it's good to go!

**Comment by jrg94** [comment]
Sounds good! I'll probably make some shell pun and add the typical text over the image. Any of these images you like in particular:

1. https://pixabay.com/en/conch-shell-shell-sea-shell-beach-3432711/
2. https://pixabay.com/en/shell-sand-sea-shells-summer-1920672/
3. https://pixabay.com/en/shell-sand-beach-sea-holiday-523944/

**Comment by Alcha** [comment]
I'm personally fond of [the third one][1] out of the three. 

[1]: https://pixabay.com/en/shell-sand-beach-sea-holiday-523944/

**Comment by jrg94** [comment]
I'll add the picture when you're done editing, and I'll set everything up to publish tomorrow morning.

**Comment by jrg94** [comment]
Alright, everything is set up for publishing tomorrow at 10AM: https://therenegadecoder.com/code/hello-world-in-powershell/

In the meantime, feel free to update your profile on the site. There's a box at the bottom that automatically displays social media links and profile information.

**Comment by Alcha** [comment]
Ahh, that's what I forgot to do lol. It's been updated and should be good to go now 😊

**Comment by jrg94** [comment]
By the way, I updated the link in the README to the article.
