### ISSUE TITLE
Inclusive Language Update in Articles

### ISSUE THREAD

**Issue by jrg94** [jrg94/sample-programs#205]
@AaronLenoir made a great point about my usage of 'simply' and 'just' throughout the repo. I want to take a moment to scan through my series of articles and update the language to remove these terms.

**Comment by jrg94** [comment]
I find that often use these terms a scapegoat. Not because I think that the subject is easy, but rather that I'm too lazy to actually write up directions. 😆 

At any rate, this will help me immensely moving forward. Thanks for the support.

**Comment by AaronLenoir** [comment]
Good point.

I usually use "simply" and "just" in an attempt to reassure the people they are talking to that they will be able to get it: "_don't worry, you think it's hard but it's not too bad_". But it can have the opposite effect or be condescending.

Even though I immediately notice when I hear or read it, I still catch myself doing it sometimes. Was reminded about it recently by [this tweet](https://twitter.com/jesstelford/status/992756386160234497) doing the rounds.

**Comment by jrg94** [comment]
Great reference. I might add those to my spellcheck as bad words haha

**Comment by jrg94** [comment]
Copying those words here for reference:

- obviously
- basically
- simply
- of course
- clearly
- just
- everyone knows
- however
- so,
- easy

Also, here's the article: https://css-tricks.com/words-avoid-educational-writing/

**Comment by jrg94** [comment]
Adding a list of articles, so I can track the proofreading:

- [ ] [Hello World in Python](https://therenegadecoder.com/code/hello-world-in-python/)
- [ ] [Hello World in Java](https://therenegadecoder.com/code/hello-world-in-java/)
- [ ] [Hello World in C](https://therenegadecoder.com/code/hello-world-in-c/)
- [ ] [Hello World in C++](https://therenegadecoder.com/code/hello-world-in-c-plus-plus/)
- [ ] [Hello World in C#](https://therenegadecoder.com/code/hello-world-in-c-sharp/)
- [ ] [Hello World in Ruby](https://therenegadecoder.com/code/hello-world-in-ruby/)
- [ ] [Hello World in Objective-C](https://therenegadecoder.com/code/hello-world-in-objective-c/)
- [ ] [Hello World in Swift](https://therenegadecoder.com/code/hello-world-in-swift/)
- [ ] [Hello World in Go](https://therenegadecoder.com/code/hello-world-in-go/)
- [ ] [Hello World in Rust](https://therenegadecoder.com/code/hello-world-in-rust/)
- [ ] [Hello World in JavaScript](https://therenegadecoder.com/code/hello-world-in-javascript/)
- [ ] [Hello World in PHP](https://therenegadecoder.com/code/hello-world-in-php/)
- [ ] [Hello World in Lisp](https://therenegadecoder.com/code/hello-world-in-lisp/)
- [ ] [Hello World in Scheme](https://therenegadecoder.com/code/hello-world-in-scheme/)
- [ ] [Hello World in Racket](https://therenegadecoder.com/code/hello-world-in-racket/)
- [ ] [Hello World in Haskell](https://therenegadecoder.com/code/hello-world-in-haskell/)
- [ ] [Hello World in Perl](https://therenegadecoder.com/code/hello-world-in-perl/)
- [ ] [Hello World in Scala](https://therenegadecoder.com/code/hello-world-in-scala/)
- [ ] [Hello World in Elixir](https://therenegadecoder.com/code/hello-world-in-elixir/)
- [ ] [Hello World in Pascal](https://therenegadecoder.com/code/hello-world-in-pascal/)
- [ ] [Hello World in Hack](https://therenegadecoder.com/code/hello-world-in-hack/)

**Comment by jrg94** [comment]
Haven't touched this in a good two months. It may be better to address the inclusive language as issues arise. Feel free to proofread my articles and make issues for each problem you see.

**Comment by jrg94** [comment]
Marked as wontfix, so we can address these issues on a case-by-case basis.
