### ISSUE TITLE
Potentially Host Article Collection on GitHub

### ISSUE THREAD

**Issue by jrg94** [jrg94/sample-programs#242]
@cottonsean wanted to make some corrections to some articles, and I think it might be fun to find a way to host those articles here. After all, they could pretty much just be in markdown.

There are some roadblocks that I already foresee. For instance, I use the Enlighter plugin for code which wouldn't translate well unless we use the raw HTML:

```
<pre class="EnlighterJSRAW" data-enlighter-language="js">alert("Hello, World!")</pre>
```

Also, I use a series plugin which would need to be manually setup before plublishing.

At any rate, I believe there is a plugin to host WordPress articles on GitHub, so I'll look into it.

**Comment by jrg94** [comment]
Apparently, this may do the trick: [WordPress GitHub Sync](https://wordpress.org/plugins/wp-github-sync/) 

It's a bit outdated (last updated 9 months ago), but seem like it would do the job:

> 1. Allows content publishers to version their content in GitHub, exposing “who made what change when” to readers
> 2. Allows readers to submit proposed improvements to WordPress-served content via GitHub’s Pull Request model
> 3. Allows non-technical writers to draft and edit a Jekyll site in WordPress’s best-of-breed editing interface

**Comment by jrg94** [comment]
I installed the plugin, but it seems overly simplistic. I'd like to be able to select which posts I import by hand.

**Comment by Alcha** [comment]
So is the end goal to host the articles on GitHub and have them accessible via [TheRenegadeCoder][0] website? 

We could just use [Pages][1] for displaying the articles unless we _need_ them to work on [TheRenegadeCoder][0] as well.

[0]: https://therenegadecoder.com/
[1]: https://pages.github.com/

**Comment by jrg94** [comment]
Ideally, I'd like to keep the articles hosted on TheRenegadeCoder since I imagine I'll be writing most of them (unless the community blows up...). That said, I'm toying with the idea of having those articles editable from here or another repo if needed.

**Comment by Alcha** [comment]
Would it be possible to use the plug in but have a `.gitignore` that prevents loading drafts or other directories you don't ant shared?

**Comment by Alcha** [comment]
If not.. How difficult would it be to modify the WordPress GitHub Sync plugin to not publish drafts? Then we could just fork the project and make it work that way.

**Comment by jrg94** [comment]
I think we can put this thought on hold for now. I marked it as wontfix, so we can revisit the idea later if needed.
