### ISSUE TITLE
Article Typos

### ISSUE THREAD

**Issue by cottonsean** [jrg94/sample-programs#243]
Some articles contain typos. Let's clean em up!

- [x] [Reverse a String in Python](https://therenegadecoder.com/code/reverse-a-string-in-python/)
  - [x] Missing the word "you" after If at the beginning of article
- [x] [Reverse a String in Java](https://therenegadecoder.com/code/reverse-a-string-in-java/)
  - [x] "Stick" should be "stuck"

![reversejavastring](https://user-images.githubusercontent.com/8882457/41798155-9d58a1a0-763a-11e8-8c43-6a445536a9fe.png)

**Comment by jrg94** [comment]
Good eye! I'll take care of that now.

**Comment by cottonsean** [comment]
Thanks, I think I spotted a couple more.  Should I just list all of them as one issue, or submit separately?

**Comment by jrg94** [comment]
You can list them here. I'll actually update the issue and make a little checklist.

**Comment by jrg94** [comment]
I sent you a collaborator invite, so you can update that list.

**Comment by jrg94** [comment]
Haven't heard anything in a month. Closing for now.

**Comment by samdoj** [comment]
I'll do that.  I'll rewrite mine too.  Sorry, I've been pretty busy, but I'll get it done. :)
