### ISSUE TITLE
Add Article for Fizz Buzz in Python

### ISSUE THREAD

**Issue by jrg94** [jrg94/sample-programs#264]
Looking for an author to write an article for #263

**Comment by samdoj** [comment]
I'm a little confused.  I'd love to do this but it seems you already made a pr?

**Comment by jrg94** [comment]
I apologize for the confusion! Currently, this repo doesn't have support for articles. If you want to do that, I'll have to add you as an author to the website. 

Also, I'll add you as a collaborator, so I can officially assign this to you. 😃

**Comment by samdoj** [comment]
I'm definitely still interested. :)

**Comment by jrg94** [comment]
Great! Send an email address that works for you to jeremy.grifski@therenegadecoder.com. Then, I'll get you added!

**Comment by samdoj** [comment]
Hey, I've completed the article, but I'm not sure how to add a feature image and submit it for review.

**Comment by jrg94** [comment]
Awesome! I'll have to add the featured image myself. Do you have any preference for images? I typically use free images from [Pixabay](https://pixabay.com/).

Also, your article is kind of unique because I don't have a series setup for it on the site yet. Because of that, we're looking at a publishing date of July 25th for your article.

**Comment by jrg94** [comment]
Added link to this issue in language README: https://github.com/jrg94/sample-programs/commit/ccbb222ae120100b204b278866f290072b71e814

**Comment by samdoj** [comment]
Sorry my life's been a bit chaotic this week.  I will likely do it today, but Monday at the latest.

**Comment by samdoj** [comment]
Okay, I rewrote it in the recommended style.    I think it reads better, and it tries to explain some Python concepts.

**Comment by jrg94** [comment]
I'll take a look! Since this would be the first article in a new series, I'll have to write the opening article which may take a bit. Just a heads up!

**Comment by jrg94** [comment]
I edited the article a bit, let me know how you like it! :) We're looking at a publishing date of probably August 31st. Sorry that it's so far away! There's a lot of articles schedule for August.

**Comment by samdoj** [comment]
I can't see the article at all, as I think I no longer own it, but I'm sure it's good.  :)  I can't wait to see it.
