### ISSUE TITLE
Add Hello World in Clipper

### ISSUE THREAD

**Issue by jrg94** [jrg94/sample-programs#266]
Wiki: https://en.wikipedia.org/wiki/Clipper_(programming_language)

**Comment by shoutoutloud** [comment]
Hi. Can I take up this issue?

**Comment by jrg94** [comment]
Of course! I can't officially assign it to you until I add you as a collaborator. If you make a pull request, I'll merge your change. 👍

**Comment by shoutoutloud** [comment]
Okay.Thanks.
