### ISSUE TITLE
Build up Wiki

### ISSUE THREAD

**Issue by jrg94** [jrg94/sample-programs#270]
Hey @Alcha, I recall you had some ideas for the Wiki (#246), and I was wondering if you wanted to start building up that resource.

**Comment by Alcha** [comment]
Hey @jrg94, I started on the wiki but wanted some input before I spent the time typing up the last few pages. The format is really simple and easy to follow and any changes can be easily made going forward:

https://github.com/jrg94/sample-programs/wiki

**Comment by jrg94** [comment]
I'm more than satisfied with it! If anything, I might want to add a couple columns just for credit to the contributors/authors, but those don't have to go in right now.

**Comment by jrg94** [comment]
What's the plan for languages that have multiple articles? There's not many now, but I'm curious.

**Comment by Alcha** [comment]
We could modify the columns to be **Hello World Article** and **Other Article Name**, or if it gets too complex then we can switch from tables to outline style.

- Language Name
  - Repo link
  - Article A Link
  - Article B Link
  - Etc...

**Comment by jrg94** [comment]
To be honest, I prefer the tables. What if we pointed to the language tag on the website (i.e. [Pascal](https://therenegadecoder.com/tag/pascal/))? As long as all the articles are tagged appropriately, they would show up there. Then, we can rename the column to **Articles**.

**Comment by jrg94** [comment]
Another column I'd be interested in would be a column for open issues related to that language. Not essential, but possibly a nice-to-have.

**Comment by Alcha** [comment]
Sure, I'll update the existing languages to show some of these new tables so we can see it in action.

**Comment by jrg94** [comment]
I like how this looks especially with the links in the languages column. Also, the issues column is great, but the linking doesn't appear to work the way we'd like it to work. Might have to include absolute links there.

As for the article links, I think the tag page is going to work best. The links can be added once and never need to be maintained. I added an example under Go.

**Comment by jrg94** [comment]
Did some playing with G! Let me know if that looks alright.

**Comment by jrg94** [comment]
Alright, I actually added a contributors column to G. Does that look okay?

**Comment by Alcha** [comment]
Yeah, that does actually look really nice. Well done! 👍 

In that case, I'll go ahead and update the rest here shortly and push the changes.

**Comment by jrg94** [comment]
Let me know if you need any help with the tag pages. The looks should look like the following:

`therenegadecoder.com/tag/<language>`

Alternatively, you can find the tag link at the bottom of each of the language articles, hopefully. haha

**Comment by Alcha** [comment]
Alrighty, I didn't get around to it as soon as intended, but I finally did. I've submitted the final files to get the ball rolling, lemme know what you think: https://github.com/jrg94/sample-programs/wiki

**Comment by jrg94** [comment]
Love it! Thanks for all that. I think that will go a long way to helping with the organization of the repo.

**Comment by jrg94** [comment]
I'll close this for now and hopefully we can keep the repo maintained.

**Comment by Alcha** [comment]
I couldn't agree more. I think having a Wiki will be a great help with increased contributions, specifically due to the issues column (glad you came up with that!) 

I'll keep an eye on it and see if I can't write a script or something to automatically add new additions to the wiki. We'll just have to add issues/articles to the tables manually.

**Comment by jrg94** [comment]
I love the script idea! It would be nice to automate the Wiki if possible.
