### ISSUE TITLE
Add Article for Hello World in Opa

### ISSUE THREAD

**Issue by jrg94** [jrg94/sample-programs#281]
Alright, I just added @nicovillanueva to the site. For now, I'm going to update the README to remove the `how to` section and include a link to this issue as mentioned in #279. Once the article is written, we can update the link.

Also, I was just thinking... Maybe we can add a new section to your article just for Docker. That way, you can explain the dockerfile and explain how to build an image with it. Let me know if that makes sense.

**Comment by jrg94** [comment]
Also, here's a copy of the `how to` section:

```
## How to run

0. To avoid installing dependencies, you can use [Docker](https://docs.docker.com/install/)
1. To compile the `hello-world.opa` file, `cd` into the file's location and run: `docker run -it --rm -v $PWD:/data/ nicovillanueva/opalang:1.1.1 opa /data/hello-world.opa`
2. The compiled file will be `hello-world.js`. Run it via: `docker run -it --rm -v $PWD:/data/ -p 8080:8080 nicovillanueva/opalang:1.1.1 sh -c '/data/hello-world.js'` (or locally, installing the required npm modules)
3. Go to http://localhost:8080
```

**Comment by nicovillanueva** [comment]
I'm far from being a tech writer, so please proof-read it and edit as much as you want. Also keep in mind that English is not my first language, so I might write in a weird way sometimes.
Also, as I didn't want to screw anything up, I left it as a draft: https://therenegadecoder.com/?p=11114

**Comment by jrg94** [comment]
No worries! I'll take a look.

**Comment by jrg94** [comment]
Hey! I think your article looks great. I took a moment to reorganize it slightly to match the style of other articles in the series. As a result, there are a couple new empty sections. For instance, I there's a Hello World in Opa section which you could use to explain the code. I kept your execution section as-is. 

Let me know if you need anything! 👍

**Comment by jrg94** [comment]
Not yet! I was wondering if you could fill out the Hello World in Opa section with a copy of the solution and a brief description on how it works.

**Comment by jrg94** [comment]
For the featured image, how would you feel about a picture of Greece? That'll serve as a play on "Opa" which is also apparently [a Greek expression](https://en.wikipedia.org/wiki/Opa!_(Greek_expression)).

![Opa!](https://cdn.pixabay.com/photo/2014/08/12/00/01/oia-416136_1280.jpg)

**Comment by nicovillanueva** [comment]
Hey, I just added the solution itself, and a very brief description of it.
Also, the pic looks great!

**Comment by jrg94** [comment]
Great! I'll take a look. Thanks for your help 💯

**Comment by jrg94** [comment]
Don't forget to update your profile :) it shows up at the bottom of your post.

**Comment by jrg94** [comment]
By the way, I'll be publishing your article at 10:00AM Eastern Time on July 25th, 2018.

**Comment by jrg94** [comment]
Alright! Article is scheduled. I've also updated the README. Closing this for now :)
