### ISSUE TITLE
README.md Support section link issue

### ISSUE THREAD

**Issue by Alcha** [jrg94/sample-programs#282]
Hey @jrg94, I noticed there's a link to "Use The Renegade Coder Shop" in the Support section of the README.md file:

![image](https://user-images.githubusercontent.com/6931731/43020117-91a9b79a-8c24-11e8-80fe-c356838b7f7e.png)

When clicking the link it takes you to the home page of https://therenegadecoder.com, and on the home page is a button with a link to the "shop" again, but none of these links actually go to a store.

**Comment by jrg94** [comment]
Yeah, that's my bad. I just removed the store from the website, and I haven't gone through the process of cleaning those sorts of things up.

**Comment by jrg94** [comment]
I just removed the link from the README and I updated the links on the homepage. I have to go through and polish up the [5 Ways to Support The Renegade Coder](https://therenegadecoder.com/blog/5-ways-you-can-support-the-renegade-coder/) article.

**Comment by Alcha** [comment]
I figured it was a simple mistake, glad to hear it's been _mostly_ resolved 😅

**Comment by jrg94** [comment]
Yup! I was going through a phase of simplifying the site and decided it didn't make sense for me to maintain a store anymore. I ended up removing the store, but there were some dead links floating around.

I think everything is resolved now. 🙏

**Comment by jrg94** [comment]
Looks like I perhaps missed the biggest shop link on the homepage. Whoops!
