### ISSUE TITLE
Alert Everyone of New Registration Link

### ISSUE THREAD

**Issue by jrg94** [jrg94/sample-programs#290]
Hey! Just so everyone is aware, I've officially opened up a membership section on my site. No longer will you need to give me an email, so I can manually create an account for you. Instead, you can quickly go to [the registration page](https://therenegadecoder.com/membership-join/membership-registration/) and create an account. From there, let me know, so I can elevate your privileges.

For anyone who already has an account, I attempted to import your data directly into the new membership database. Apparently, the plugin I chose to use runs a separate membership database, so I'm not sure how things will mesh with your previous accounts. I will say that the new registration form will create an account in both tables, so you're probably fine. That said, don't be surprised if you have to reset your password. 

Please take a moment to try to [login](https://therenegadecoder.com/membership-login/). I believe the admin bar at the top of the screen will now be hidden from you, so it may be a good idea to [bookmark the backend](https://therenegadecoder.com/wp-admin/) for drafting articles. I hid the admin bar so regular subscribers aren't digging around the backend (not that they can see anything), and so they don't feel confused with the addition of the bar. 

If you're wondering, membership doesn't affect anyone who uses the repo unless they want to comment on a post. I've decided to require membership for my blog (the category) posts in case anyone wants to get to know me a bit better. All the coding articles are still free forever. In the future, I plan to put a pay wall between some of the more questionable blog posts. That money will go back into the site.

**Comment by Alcha** [comment]
I was able to log in without issue so no worries w/ me 👍

**Comment by jrg94** [comment]
Good to know! Thanks for the quick response. I think I'm going to add the backend link to the contribution article in case people are lose it.

**Comment by jrg94** [comment]
Alright, I've been polishing all these details today. With the change, comes an email list. Y'all will get your first recurring email on Friday. It just includes all the articles from the last week. Feel free to unsubscribe if it bugs ya!
