### ISSUE TITLE
Create Chronological Wiki Table

### ISSUE THREAD

**Issue by jrg94** [jrg94/sample-programs#299]
I'm interested in finding other ways to organize the current data. For instance, it would be cool to have a chronological table to organize the languages by the year they came out.

The main problem is, however, that we're going to end up with a lot of duplicate information. In other words, we might have a table where Python appears under "P" as well as "1991." As a result, any changes to one table would need to be made in the other. 

I'm wondering if there's a better way to handle this.

**Comment by jrg94** [comment]
Perhaps, we can make a general meta data table, so we don't have duplicate information floating around.

**Comment by jrg94** [comment]
It's really too bad we can't automate some of this. Even if someone could draft up a Python script just to generate parts of the wiki, that would be nice.

**Comment by jrg94** [comment]
Found a [python markdown API](https://github.com/Python-Markdown/markdown), but I think it's used for web. I'm not sure it'll be helpful here.

**Comment by Berkmann18** [comment]
You could (in theory) automate that but as you said, it would lead to duplicate content unless the repo uses **one** way (say alphabetically like it is now) and on the webpage where this repo is usable (say on a GH page) then it could have an option that users could change to set the listing way (date of apparition or alphabetically or ...).

**Comment by jrg94** [comment]
Others have mentioned GitHub pages in the past. Does that seem like a better idea than to host a wiki?

**Comment by Berkmann18** [comment]
@jrg94 Well, it might be better when it comes to dynamic things such as that but for static information than a wiki would be fine.

**Comment by jrg94** [comment]
Closing as duplicate.
