### ISSUE TITLE
Write Script to Generate Wiki Boilerplate

### ISSUE THREAD

**Issue by jrg94** [jrg94/sample-programs#300]
At this point, there's A LOT of boilerplate in our wiki, and I'd like to automate that somehow. 

I'm a huge fan of writing a script for this because we could eventually add even more features to it. How cool is that?!

**Comment by jrg94** [comment]
Perhaps we can create a tools folder and drop the script in there.

**Comment by Berkmann18** [comment]
It depends on what exact tasks and how you want to automate them.
I would be happy to help as I like automating things (and said I'll have a look at this repo on dev.to).

**Comment by jrg94** [comment]
I want to take a stab at "automating" the wiki. I'm interested in trying to replicate what we already have through a script, so someone could theoretically just run the script as needed and commit the changes. It might even be nice to automate the wiki building through Jenkins or something, but I'm happy with a working script that we have to manually trigger for now.

**Comment by Berkmann18** [comment]
Another (although still new in GH) would be to have a bot (say a [probot](https://github.com/probot)) that will do that or at least the legwork and leave the review/confirmation bit to contributors (like you have with PR checkers).

**Comment by jrg94** [comment]
Wow, that's really cool. I like that idea. I'd be interested in learning TypeScript just to fool around with one of those bots.

**Comment by jrg94** [comment]
For the moment, I'm going to toy around with generating a few markdown pages in Python. If that ends up being a waste of time, I'll look for some help with the probot idea.

**Comment by jrg94** [comment]
I ended up merging in a simple Python script that does some basic analysis of the repo. Unfortunately, it doesn't even scratch the surface in terms of what I'd like to do.

For instance, I'd like to be able to document a list of issues associated with the various languages as well as their contributors. All the analytics I've done so far is bonus, honestly. The GitHub related stuff is actually practical but more complicated in terms of local scripting. Perhaps the probot is the way to go.

**Comment by Berkmann18** [comment]
>I'd like to be able to document a list of issues associated with the various languages as well as their contributors

Was that using labels or keywords in the titles associated to each languages?

**Comment by jrg94** [comment]
Language keywords. That would probably be too many labels otherwise.

**Comment by Berkmann18** [comment]
Ah I see.

**Comment by jrg94** [comment]
I think I can automate that actually. Instead of linking individual issues, we can link a query string that looks for the language keyword. That should be solid enough!

**Comment by Berkmann18** [comment]
That looks good to me.

**Comment by jrg94** [comment]
As a summary, the script seems to work great! I'd love to clean it up before adding new features, but for now it does the job.
