### ISSUE TITLE
Automate Wiki Building

### ISSUE THREAD

**Issue by jrg94** [jrg94/sample-programs#306]
Now that we have a decent script for building the wiki, I'd to run a service like Jenkins or Travis CI which runs the script and uploads the new wiki after every commit to master. I assume this is doable, but we'll see.

**Comment by jrg94** [comment]
I'm currently looking into Travis CI. Ideally, I'd like: 

1. Clone this repo
2. Generate the wiki files
3. Clone the wiki
4. Overwrite the existing wiki files with the new ones
5. Push the wiki changes

Hopefully, that workflow is possible.

**Comment by Alcha** [comment]
Just to verify, when you say we have a script for building the wiki do you mean the [`generate-wiki.py`][0] file in the **Tools** directory?

[0]: https://github.com/jrg94/sample-programs/blob/master/tools/generate-wiki.py

**Comment by jrg94** [comment]
Yup! It does almost everything we had already (except contributors) with some added features. 💯  

It's a little ugly, but it gets the job done. If the continuous integration stuff proves too complicated, I'm interested in trying to replicate [`generate-wiki.py`][0] in TypeScript to make a probot! Of course, I haven't looked into that at all, so I'm not sure what is even possible. 

[0]: https://github.com/jrg94/sample-programs/blob/master/tools/generate-wiki.py

**Comment by Alcha** [comment]
Ooo... I'd be quite interested in converting it to TypeScript just out of sheer desire to learn TypeScript. If I get around to doing so I'll be sure to submit an issue/PR for it for easier discussion/tracking.

**Comment by jrg94** [comment]
Alright, Travis CI has been fully outfitted to automate the Python script. It took much longer than I would have liked to work out the kinks, but I'm happy with it. Now, I believe anytime someone commits to master, the wiki will be rebuilt.
