### ISSUE TITLE
Add Game of Life in TypeScript

### ISSUE THREAD

**Issue by juanfrank7** [jrg94/sample-programs#309]
I recently came across a post about the "Game of Life" and it made me think about it would be cool implementing it as part of the sample programs. However this time I'd like to do it in Typescript as opposed to JavaScript for 1. contributing to a different language and 2. dusting off my kinda rusty Typescript skills at the moment haha. I might be able to finish it this weekend :)

**Comment by Alcha** [comment]
I can't *wait* to see this! I've been obsessed with the Game of Life ever since I saw it in this repo but I've yet to really wrap my head around it. Seeing it implemented in TS would help me immensely.
